name: pull-request-workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.13.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.13.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:coverage
